#!/bin/bash
if [[ -z "$(command -v git)" ]]; then
	echo "Could not find git. Exiting."
	exit 
fi

echo "# VERSION generated by $(whoami) on $(date) from $(hostname)" > VERSION

echo "git.branch = $(git symbolic-ref HEAD)" >> VERSION
echo "git.commit = $(git rev-parse HEAD)" >> VERSION

echo "build.hostname = $(hostname)" >> VERSION
echo "build.date = $(date)" >> VERSION
echo "build.user = $(whoami)" >> VERSION

# mkdir -p resources
# mv VERSION resources/
