/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package com.turn.splicer.tsdbutils.expression.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

	/**
	 * End of File.
	 */
	int EOF = 0;
	/**
	 * RegularExpression Id.
	 */
	int NAME = 5;
	/**
	 * RegularExpression Id.
	 */
	int PARAM = 6;

	/**
	 * Lexical state.
	 */
	int DEFAULT = 0;

	/**
	 * Literal token values.
	 */
	String[] tokenImage = {
			"<EOF>",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
			"<NAME>",
			"\"&&\"",
			"\"(\"",
			"\",\"",
			"\")\"",
			"\":\"",
			"\"{\"",
			"\"=\"",
			"\"}\"",
	};

}
